version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: halo-blockscout-db
    command: postgres -c max_connections=200 -c shared_buffers=256MB
    environment:
      POSTGRES_PASSWORD: 'halochain'
      POSTGRES_USER: 'blockscout'
      POSTGRES_DB: 'blockscout'
    volumes:
      - blockscout-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    container_name: halo-blockscout-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: blockscout/blockscout:latest
    restart: always
    container_name: halo-blockscout-backend
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      # Database
      DATABASE_URL: 'postgresql://blockscout:halochain@db:5432/blockscout'
      POOL_SIZE: '50'
      POOL_SIZE_API: '10'

      # Redis
      REDIS_URL: 'redis://redis:6379'

      # Network
      NETWORK: 'Halo Chain'
      SUBNETWORK: 'Mainnet'
      CHAIN_ID: '12000'

      # RPC endpoints - Using host network gateway
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      ETHEREUM_JSONRPC_HTTP_URL: 'http://172.17.0.1:8545'
      ETHEREUM_JSONRPC_WS_URL: 'ws://172.17.0.1:8545'
      ETHEREUM_JSONRPC_TRACE_URL: 'http://172.17.0.1:8545'

      # Indexer settings - Archive node configuration
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'false'
      INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE: '10'
      INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY: '2'
      INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: '10'
      INDEXER_CATCHUP_BLOCKS_CONCURRENCY: '1'

      # Block time
      BLOCK_TIME: '1'

      # Features
      ENABLE_TXS_STATS: 'true'
      SHOW_PRICE_CHART: 'false'
      SHOW_TXS_CHART: 'true'
      DISPLAY_TOKEN_ICONS: 'true'

      # Coin settings
      COIN: 'HALO'
      COIN_NAME: 'Halo'

      # UI Settings
      LOGO: '/images/blockscout_logo.svg'
      LOGO_FOOTER: '/images/blockscout_logo.svg'

      # Secret key base (generate a new one with: openssl rand -base64 64)
      SECRET_KEY_BASE: 'M6w5Z1YG3uYeRLYIEzadExlBc5Crik7neBmcQc/hzE+2JP6MX/D4CmKNp0CeqQHCiJV26eqGw0d5cBRaxQpWEw=='

      # API rate limit
      API_RATE_LIMIT_DISABLED: 'false'
      API_RATE_LIMIT: '50'
      API_RATE_LIMIT_TIME_INTERVAL: '1s'

      # Additional settings
      HEART_BEAT_TIMEOUT: '30'
      HEART_COMMAND: 'systemctl restart explorer'

      # EIP-1559
      EIP_1559_ENABLED: 'true'

      # Archive node features
      TRACE_FIRST_BLOCK: '1'
      TRACE_LAST_BLOCK: 'latest'

      # Frontend configuration
      BLOCKSCOUT_HOST: 'localhost'
      BLOCKSCOUT_PROTOCOL: 'http'

      # Ecto settings
      ECTO_USE_SSL: 'false'

      # Port
      PORT: '4000'

    ports:
      - "4000:4000"
    volumes:
      - ./blockscout-logs:/app/logs

  frontend:
    image: ghcr.io/blockscout/frontend:latest
    restart: always
    container_name: halo-blockscout-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_APP_HOST: 'localhost'
      NEXT_PUBLIC_API_HOST: 'localhost'
      NEXT_PUBLIC_API_PORT: '4000'
      NEXT_PUBLIC_API_PROTOCOL: 'http'
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: 'ws'
      NEXT_PUBLIC_STATS_API_HOST: 'http://localhost:4000'
      NEXT_PUBLIC_NETWORK_NAME: 'Halo Chain'
      NEXT_PUBLIC_NETWORK_SHORT_NAME: 'Halo'
      NEXT_PUBLIC_NETWORK_ID: '12000'
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: 'Halo'
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: 'HALO'
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: '18'
      NEXT_PUBLIC_IS_TESTNET: 'false'
    ports:
      - "3000:3000"

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:latest
    restart: always
    container_name: halo-smart-contract-verifier
    environment:
      SMART_CONTRACT_VERIFIER__SERVER__HTTP__ADDR: '0.0.0.0:8050'
      SMART_CONTRACT_VERIFIER__SOLIDITY__ENABLED: 'true'
      SMART_CONTRACT_VERIFIER__SOLIDITY__COMPILERS_DIR: '/tmp/solidity-compilers'
      SMART_CONTRACT_VERIFIER__SOLIDITY__REFRESH_VERSIONS_SCHEDULE: '0 0 * * * * *'
      SMART_CONTRACT_VERIFIER__VYPER__ENABLED: 'true'
      SMART_CONTRACT_VERIFIER__VYPER__COMPILERS_DIR: '/tmp/vyper-compilers'
      SMART_CONTRACT_VERIFIER__VYPER__REFRESH_VERSIONS_SCHEDULE: '0 0 * * * * *'
    ports:
      - "8050:8050"
    volumes:
      - ./verifier-cache:/tmp

volumes:
  blockscout-db-data:
    driver: local
